### ISSUE TITLE
Setup.py

### ISSUE THREAD

**Issue by znicholls** [OMS-NetZero/FAIR#1]
Setup.py script so that FAIR can be installed as a module. Need to decide whether we will use setuptools or an alternative.

**Comment by richardcode** [comment]
I think standard setup tools should be fine. We should keep everything as minimal and basic as we can get away with...

**Comment by znicholls** [comment]
@richardcode 
I agree we don't want to get too caught up in things but my impression is that if you want to distribute these things you have to use either easytools or pip, both of which are built on setup tools. Having looked around a bit it seems we should stay well away from easytools e.g. [https://webvulture.wordpress.com/2011/11/12/easy_install-vs-pip/](https://webvulture.wordpress.com/2011/11/12/easy_install-vs-pip/) so I think we're going to have to get our head around how to write modules that can be distributed with pip.

For pip I think we just follow this [https://packaging.python.org/](https://packaging.python.org/). My only wonder is whether we should try and build the package for Conda instead given we're producing a scientific module... [http://conda-test.pydata.org/docs/build_tutorials/pkgs.html](http://conda-test.pydata.org/docs/build_tutorials/pkgs.html)

Have a think, whatever you decide I'm happy with.

**Comment by znicholls** [comment]
Reading this I'm leaning more towards conda [http://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda](http://stackoverflow.com/questions/20994716/what-is-the-difference-between-pip-and-conda) especially given we don't just have Python versions

**Comment by znicholls** [comment]
A good example of something similar? https://github.com/openclimatedata/pymagicc

**Comment by znicholls** [comment]
@richardcode commit `b355745d0834d48f1b3e8bbefbdc1a3ec6db2e4d` contains a setup.py file and the necessary other bits to install with setuptools. I'll write some documentation tomorrow and when you're ready we can discuss how exactly we want this all to end up looking.

**Comment by richardcode** [comment]
@znicholls I definitely agree that conda is the way forward. I try to use it when ever it is possible at the moment as it is so much better than the alternatives. Will have a play with this all when I can spend a few hours on this before bed.

**Comment by richardcode** [comment]
@znicholls did you upload this to PyPI in the end? Would be keen to make the conda recipe for building this but don't want to duplicate anything that you've done already. Your setup.py seems to work for me too!

**Comment by znicholls** [comment]
Yes on the test site here https://testpypi.python.org/pypi/fair-objo/0.0.0.dev0

I was going to follow https://conda.io/docs/building/build.html to work out how to make a conda package but haven't done so yet. Notes on PyPI/pip packaging coming soon hopefully.

**Comment by znicholls** [comment]
Sorry here is the command to install from the test site

`pip install -i https://testpypi.python.org/pypi fair_objo`
