### ISSUE TITLE
Calculation of CO2 concentrations relative to aviation

### ISSUE THREAD

**Issue by fracamil** [OMS-NetZero/FAIR#100]
Dear all,

I began to learn how to use FaIR, firstly to better understand and to reproduce the cases demonstrating GWP* (see [“Demonstrating GWP*: a means of reporting warming-equivalent emissions that captures the contrasting impacts of short- and long-lived climate pollutants”](https://iopscience.iop.org/article/10.1088/1748-9326/ab6d7e#references)) and secondly to integrate the aviation CO2 emissions and ERF models extracted from the supplementary data from Lee et al. 2021 (see [“The contribution of global aviation to anthropogenic climate forcing for 2000 to 2018"](https://www.sciencedirect.com/science/article/pii/S1352231020305689) to estimate the impact of future aviation emissions scenarios coupled calculated with the CAST simulator (see [https://cast.isae-supaero.fr/](https://cast.isae-supaero.fr/)).

Unfortunately, I cannot reproduce the CO2 aviation concentration and ERF results mentioned in Lee et al. 2021. Here is the method I used and the result I obtained:

- FaIR v1.6 with default parameters, “myhre” method used to calculate ERF for CO2, CH4 and N2O (similar to the method described in the IPPC report cited in Lee and al. 2021 in chapter 4.1);
- Injection of the global aviation CO2 emissions on top of the RCP45 CO2 emissions (based on Sausen and Schumann, 2000 + supplementary data of the publication);
- I obtain a CO2 concentration value related to aviation in 2018 of 8.87 ppm (3.63 higher than the value provided by Lee and al.). The same factor amplitude (close to 3.61) can be found for the 2005 and 2011 values. The CO2 ERF value given by FaIR is higher than the value provided in the paper.

I am quite lost and am sure I am missing an important point or method, to calculate the contribution of some CO2 emissions to the global CO2 concentration. This is probably due to my lack of experience in using climate models (but I am learning quickly!).

I thank you in advance for your answer or advices, 

Best regards,

Francois

**Comment by chrisroadmap** [comment]
Hello @fracamil,

The factor of 3.63 difference could explain things. FaIR takes emissions of CO2 in units of GtC (rather than GtCO2). Are you reporting the change in CO2 emissions in GtCO2? Dividing this by 3.664 will give you GtC, which will be close to the differences you are experiencing. If it's not this, could you send a code snippet?

Chris

**Comment by fracamil** [comment]
Hello @chrisroadmap,

I thank you for your quick answer which has been very helpfull. 

You were right, the emissions I used were reported in GtCO2 and not in GtC (what a silly mistake!). After introducing the conversion in GtC of the input I use, the results I obtain are very close to those reported by Lee and al. in their 2021 paper. 

I will be able from now on to implement contrail forcing based on Lee and al. 2021 paper by passing externally estimated  forcing values as argument (contrail_forcing='external',F_contrails = _externally calculated values vector_), along with other of aviation induced climate forcers. It will maybe be a little bit difficult regarding the implementation of NOx radiative forcing but I will find out. 

Best regards,

Francois

**Comment by chrisroadmap** [comment]
It looks like this answered the question, so I'll close this now.
