### ISSUE TITLE
cannot import fair modules after installing

### ISSUE THREAD

**Issue by aliss77777** [OMS-NetZero/FAIR#148]
Hi!

I am following the recommended steps by running `pip install fair`. I've also tried this in a virtual environment and on a cloud Google Collab noteook. 

When attempting to import specific modules (the command below) I get an error no module found:
```
from fair.RCPs import rcp85
```

When I look at the folder structure I have installed, I don't see the RCP module. Here's what I see:
<img width="869" alt="Screenshot 2023-11-30 at 4 04 33 PM" src="https://github.com/OMS-NetZero/FAIR/assets/4154159/5a1e265e-868a-4e6b-8c44-2524722e4010">

This is not good! I want to see something like the picture below. This is what the folder structure looks like on the github branch below, there is a subfolder fair which then contains a subfolder with the RCP's module. How can I fix this?

<img width="914" alt="Screenshot 2023-11-30 at 4 07 15 PM" src="https://github.com/OMS-NetZero/FAIR/assets/4154159/81873db5-670c-4b55-bd01-c432b872c794">

<img width="1553" alt="Screenshot 2023-11-30 at 4 07 56 PM" src="https://github.com/OMS-NetZero/FAIR/assets/4154159/3b1ed42b-da11-43f3-bb2d-6ce895cf3e65">

Thank you 🙇🏻‍♂️

**Comment by rgieseke** [comment]
1.6.4 changed the interface to include SSPs. Which version of FaIR did you install?

https://github.com/OMS-NetZero/FAIR/releases

**Comment by chrisroadmap** [comment]
you can always pin your version

`pip install fair==1.6.4`

when installed you can check which version you're running

```
>>> import fair
>>> fair.__version__

'2.1.3'
```

version 2.0+ changes the interface and doesn't include these RCP (or SSP) imports now

ta
chris

**Comment by aliss77777** [comment]
got it thanks! I'm attempting to use the Project Drawdown solution repo (https://github.com/ProjectDrawdown/solutions) and realizing it has not been updated in a while and requires older versions of key libraries like FAIR.  If you have worked with that repo at all and know anyone who might be maintaining it I would love to get connected

**Comment by chrisroadmap** [comment]
I've spoken to them once a while ago but I'm not involved. Without looking can you just create a fork and modify the dependencies in your own fork to pin the version of fair?

**Comment by chrisroadmap** [comment]
I'll close as relates to an old issue and the dependency is in another repository.
