### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by milankl** [OMS-NetZero/FAIR#154]
Hi Chris, quick question on the versioning here. I see from the release notes what has changed between 2.0 and 2.1 and going towards 2.2 but are you using semantic versioning and if yes, what counts as a breaking change? Same interface or qualitatively/quantitatively same model results?

**Comment by chrisroadmap** [comment]
Semantic versioning was inconsistently implemented prior to v2.1 and that is a breaking change relative to v2.0, but we wanted to highlight the versions qualitatively aren't that different. From now on, we promise no breaking changes without a new major version.

**Comment by milankl** [comment]
Awesome, thanks. I generally don't consider changing model results as breaking change, more like a bug fix assuming you improve the model somehow -- especially not if the qualitative results are comparable. Also because while results may differ it's not a throwing error that would break a users code. Interface changes however, I do consider as breaking change.

**Comment by chrisroadmap** [comment]
If only I knew in 2019 what I know now.

**Comment by chrisroadmap** [comment]
I'll close this issue, since I don't think it causes any problems.
