### ISSUE TITLE
Zenodo releases

### ISSUE THREAD

**Issue by rgieseke** [OMS-NetZero/FAIR#17]
Maybe you have already been planning this, but since you're already doing these nice releases (incl. Changelog info) it would be very little effort to add Zenodo archiving and DOI minting to FAIR:

https://guides.github.com/activities/citable-code/

That way you could also refer to an archived version in the final version of the paper.

**Comment by chrisroadmap** [comment]
@richardcode @znicholls any chance one of you could enable third party access to Zenodo on OMS-NetZero if you're happy? Would be really nice to have a DOI for this.

**Comment by znicholls** [comment]
Done.
