### ISSUE TITLE
Start using versioneer

### ISSUE THREAD

**Issue by znicholls** [OMS-NetZero/FAIR#2]
The way we're doing things at the moment is not the smartest I don't think. Given how slow development is it's not really an issue but `versioneer` seems to be a good option if it does become an issue. 

https://github.com/warner/python-versioneer

**Comment by chrisroadmap** [comment]
I've added a branch (add_versioneer) in which I've set up `versioneer`. It appears to work. I **think** that each developer would need to install `versioneer` themselves locally, but once done my understanding is that it should automatically tag revisions once changes are committed. Let me know if you're happy to merge in.

**Comment by znicholls** [comment]
If we add `versioneer` as a dependency in `setup.py` would we skip the need for people to think about installing `versioneer` locally i.e. it would happen automatically?

**Comment by chrisroadmap** [comment]
It's my understanding that users don't need to install it as it lives in the setup script. Actually, once it's in place and configured I'm not sure developers need to install it locally either as I think `versioneer.py` handles the version tagging automatically.

**Comment by znicholls** [comment]
Ah ok yes I understand. I think you're right. I'd also be very surprised if there weren't a way to specify which modules developers need.

**Comment by chrisroadmap** [comment]
Done and merged into master.
