### ISSUE TITLE
Updating parameters once initialized

### ISSUE THREAD

**Issue by richardcode** [OMS-NetZero/FAIR#3]
We need to create some methods that all the TCR etc to the altered once initialized and then automatically recalculate the derived parameters such as q so that the model can be run again.

**Comment by znicholls** [comment]
You can reassign attributes by simply using e.g.

    t1 = FAIR() 
    t1.TCR = 2.5 
    t1.ECS = 4.5

We can solve the issue of recalculating derived parameters using properties [https://www.programiz.com/python-programming/property](https://www.programiz.com/python-programming/property). I will do this in my next commit.

**Comment by znicholls** [comment]
After commit 'd261ffea2ee494b4173fb6d69c493886e6f332c6' we can do
```
>>> from fair_main_obj_oriented import *
>>> t1 = FAIR()
Get TCR twice to calculate q when the FAIR object is initialised
getting TCR
getting TCR
>>> t1.TCR = 2.2
setting TCR
re-calculating q
getting TCR
getting TCR
>>> t1.k
array([ 0.94142857,  0.13313479])
>>> t1.q
array([ 0.61764851,  0.05080069])
>>> t1.TCR = 2.0
setting TCR
re-calculating q
getting TCR
getting TCR
>>> t1.k
array([ 0.94142857,  0.13313479])
>>> t1.q
array([ 0.55148948,  0.11695972])
```
