### ISSUE TITLE
Write script which determines atoms in species from chemical formula

### ISSUE THREAD

**Issue by znicholls** [OMS-NetZero/FAIR#3]
I have one in MATLAB, just need to dig it up. Also requires table of chemical formulas for each species name.

**Comment by chrisroadmap** [comment]
@znicholls presume good to close? All relevant chemical properties (molecular weights, fractional release for ozone, # of chlorine atoms) are included in the species configs which are user-definable.

**Comment by znicholls** [comment]
Yep sure, too long ago to worry about now haha
