### ISSUE TITLE
RCP naming

### ISSUE THREAD

**Issue by rgieseke** [OMS-NetZero/FAIR#36]
Would be nice (since Pymagicc, MAGICC and Pyhector have converged on `26`, `45`, `60`, and `85` if FAIR allowed for these too.

It would be no problem to keep `3PD` and `6` for backwards compatibility.

I'm happy to provide a PR if needed.

**Comment by chrisroadmap** [comment]
I'm about to merge in a commit which does this and also moves the data files themselves out of the RCP directory. The first step on a very long road to FaIR 2.0.
