### ISSUE TITLE
Decide naming conventions and repository structure

### ISSUE THREAD

**Issue by znicholls** [OMS-NetZero/FAIR#4]
Just in case we one day add concentration driven, temperature driven etc. etc. versions we should probably decide on a naming convention for files. Similarly we should determine a desirable repository structure (e.g. where setup files live, code etc.) at some point.

**Comment by richardcode** [comment]
Definitely agree about the repository structure. I think it would be good to have just one "source code" folder which contains all the actual scripts and then just the setup/examples/doc files living above that.

**Comment by znicholls** [comment]
Happy with our current directory structure, naming still needs to be decided on. Some prescriptions from [PEP 8](https://www.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions)

- modules and packages: short, all-lowercase names, underscores if they improve readability
- classes: CapWords convention
- Avoid using 'l' (lowercase letter el), 'O' (uppercase letter oh), or 'I' (uppercase letter eye) as single character variable names
