### ISSUE TITLE
1.3.4

### ISSUE THREAD

**Issue by rgieseke** [OMS-NetZero/FAIR#41]
Are you planning a 1.3.4 release? 1.3.3 is broken for me due to the file moving to `data`

https://github.com/OMS-NetZero/FAIR/commit/f16b9b52f2a1f8b12e439e6c73726c4b41255bc8

which was fixed in #40

**Comment by chrisroadmap** [comment]
OK, hopefully that's fixed in the new release!

**Comment by rgieseke** [comment]
Thanks! Works for me!
