### ISSUE TITLE
Add SSPs to FAIR

### ISSUE THREAD

**Issue by chrisroadmap** [OMS-NetZero/FAIR#43]
Much like the RCP emissions datasets can currently be imported, it would be good to also do this for the SSPs.

The SSP emissions files (in MAGICC SCEN format) do not appear to be publicly available yet, so would also require permission from relevant people to include within open-source FAIR.

**Comment by rgieseke** [comment]
@znicholls Do you know a timeline for this?

**Comment by znicholls** [comment]
would guess middle of next year, maybe earlier but no promises

**Comment by chrisroadmap** [comment]
That's cool - park for now

**Comment by kls2177** [comment]
Hello, any update on this? Would definitely be nice to have the SSPs. Thanks!

**Comment by chrisroadmap** [comment]
Hi Karen, currently on vacation and can do when I get back. Note that the default FaIR setup is for an AR5-like run. The aerosol and ozone assessments have changed substantially and the historical GHGs will require new "natural" balancing emissions. So yes, SSPs can be implemented, but with the caveat that results may not match either reality or the AR6 assessments in their default setups.

For some really messy examples of how FaIR v1.6 was run using SSP emissions for AR6, check out the Notebooks in the 130-160 range here: https://github.com/chrisroadmap/ar6/tree/main/notebooks

**Comment by kls2177** [comment]
Thanks for your quick reply. Ok, sounds like it may be best for me to stick with the RCPs for my purposes.

**Comment by fracamil** [comment]
Hello. Thank you @chrisroadmap for the importation inferface of the SSP. It is great to be able to try running FaIR with these inputs (which will be very usefull).

**Comment by chrisroadmap** [comment]
No problem. I'll make this a v1.6.4 release so it will be available on PyPI and Conda.

**Comment by fracamil** [comment]
Will be really great. Thanks in advance for that

**Comment by chrisroadmap** [comment]
completed in #101
