### ISSUE TITLE
Change model name to FaIR

### ISSUE THREAD

**Issue by chrisroadmap** [OMS-NetZero/FAIR#49]
Not really a bug report or feature request so not using template...

There is already a model used in the IAM community called FAIR (https://models.pbl.nl/image/index.php/Climate_policy). In order to differentiate this model from that one, the model here should now be referred to FaIR in the future. The acronym is the same with a slight re-spelling (Finite-amplitude Impulse Response model). Changes will be implemented from v1.3.5 onwards. The repository URL will remain as present, as some current publications link to it.

Because PyPI is case-insensitive, this should not make any practical difference to installing and running the model.

**Comment by znicholls** [comment]
To double check, all this requires is updates in the docs?

**Comment by chrisroadmap** [comment]
Docs and README, I think, yep.
