### ISSUE TITLE
User defined timesteps

### ISSUE THREAD

**Issue by znicholls** [OMS-NetZero/FAIR#5]
Allow the timestep to be user defined rather than being fixed at one year. 

Will require some thinking about how we do this e.g. do we let the user supply yearly emissions and then have FAIR linearly interpolate if they want to use smaller (or bigger) timesteps or do we make it that the emissions inputs define the timesteps with some flag to indicate whether the timeseries is days, months, years etc.

**Comment by richardcode** [comment]
Just found a BEAM github repository. This would be one potential way for us to go if we do want to implement this feature...
