### ISSUE TITLE
Convert to object orientation

### ISSUE THREAD

**Issue by znicholls** [OMS-NetZero/FAIR#5]
It's a shame we haven't done this already, it will make life so much easier.

**Comment by richardcode** [comment]
Very strongly agree with this. I think this needs to be a development priority for us. Few deadlines to get out of the way but when they are gone in a couple of weeks, want to put some work into an OO version of the latest master

**Comment by chrisroadmap** [comment]
I think I've basically done this now with v2.1, in a bit of a noddy fashion, but it is done all the same.
