### ISSUE TITLE
Running FaIR in Multigas Mode with many Zeros

### ISSUE THREAD

**Issue by Hans-PeterH** [OMS-NetZero/FAIR#55]
Hello,

we want to calculate how much specific companies contribute to global warming. For this we use FaIR in Multigas Mode. Until 2015 we use data from RCP2.6; from 2016 onwards we use emission data of the company (mostly only CO2) and in addition methane and nitrous oxide from natural sources (data provided by FaIR) and from agriculture (SSP database). We project the emissions of the company to a global scale using the assumption that every company worldwide has the same emission intensity (ratio of emissions to gross value added) as the company under view. We further project the data until the year 2050 using assumptions about economic growth and development of emission intensities.

If we compare the budgets for a global warming of 2 degrees to the values in the literature we find that our budgets are much too high.

I would be glad if anyone can tell us whether our approach is correct. Is it a problem that we have only Zero values from 2016 onwards for all gases except CO2, NH4 and N2O? Would it be possibly better to use CO2 only mode and add the impact of the other gases as forcings? Or are there any other ideas?

Best regards,
Hans-Peter

**Comment by chrisroadmap** [comment]
Hi Hans-Peter,

First, great that you are using FaIR for this!

> Is it a problem that we have only Zero values from 2016 onwards for all gases except CO2, NH4 and N2O? 

Potentially, yes. The level of emissions of minor GHGs and short lived climate forcers affects some of the other classes of forcers (tropospheric ozone, aerosol etc). Additionally, by setting emissions of GHGs to zero except for CO2, CH4 and N2O gives a declining atmospheric concentration of the minor GHGs, which reduces the radiative forcing from this class and hence reduces the temperature impact. So this might lead to some unexpected results. I am intending to make FaIR more flexible with regard to the choice of emissions in future.

> Would it be possibly better to use CO2 only mode and add the impact of the other gases as forcings? 

In the situation you describe, it might be. 

> Or are there any other ideas?

If you want to include the multi-gas mode, then it might be an idea to start with one of the RCP scenarios and adjust them for your particular scenario - so you have data on CO2, CH4 and N2O but let everything else follow the scenario. As you have already used RCP2.6 to drive the scenario to 2015 you could continue with that into the future.

> If we compare the budgets for a global warming of 2 degrees to the values in the literature we find that our budgets are much too high.

This is probably related to the setting other emissions to zero, but just to comment on this, budgets calculated using FaIR tend to be higher (at least if you use default values of the ECS and TCR) than some in the literature, particularly if they have been calculated using the MAGICC model. One reason is that the near-term rate of warming is lower in FaIR, which gives more headroom when analysing a 1.5 or 2C target.

**Comment by Hans-PeterH** [comment]
Hi Chris,

many thanks for your helpful comments!

**Comment by Hans-PeterH** [comment]
Hi Chris,

can you please tell me where I can change the ECS and TCR values? I haven't found it in the code. Thanks!

**Comment by rgieseke** [comment]
Hi @fuchur12 

It's the `tcrecs` parameter

https://github.com/OMS-NetZero/FAIR/blob/master/fair/forward.py#L69

As for the differences between MAGICC and FaIR it's also important to keep the reference period in mind. As mentioned by @chrisroadmap differences in the near-term rate of warming are important.
This can thus lead to differences due to picking a different reference period.

My slides from the IAMC conference last year might be helpful to you:

http://www.globalchange.umd.edu/iamc/wp-content/uploads/2019/01/gieseke.pdf

**Comment by chrisroadmap** [comment]
Awesome - cheers @rgieseke 

I'll close this issue but re-open if you have any more questions.
