### ISSUE TITLE
Flexibility of input emissions

### ISSUE THREAD

**Issue by chrisroadmap** [OMS-NetZero/FAIR#56]
**Is your feature request related to a problem? Please describe.**

It would be useful to have a choice of which emissions to run FaIR with. Currently the options are CO2-only, or all 39 species contained in the RCP databases.

**Describe the solution you'd like**

To be able to choose a subset of emissions to run FaIR that produces sensible results - a kind of intermediate step between the CO2 only and current multi-gas modes. It could either fill in the unused emissions based on some sensible and transparent assumptions, or use an additional time-varying forcing (which may be zero by default) from species not considered.

**Describe alternatives you've considered**

Setting unused emissions classes to zero is likely to give incorrect results. Running in CO2-only mode could be done but is not satisfactory when you want to investigate some non-CO2 emissions. The current best solution is to select an RCP database as the baseline case and to change only the emissions you care about, but the emissions you don't care about are still scenario-dependent.

**Additional context**

Motivated by #55

**Comment by DentonGentry** [comment]
A related point, I think: in some cases I have estimates for HFCs, but just total tonnage not broken out into individual HFC formulations. For example, AMPERE has a forecast with CO2 (Energy and Industry), CO2 (land-use change emissions), F gasses-CO2eq, CH4-CO2eq, and N2O-CO2eq. A software model I'm working on produces results in those same categories.

I could get an estimate for the percentage of each compound in common use and split up the total tonnage according to that estimate, but that means adding a degree of certainty which doesn't actually exist in my source data.

**Comment by chrisroadmap** [comment]
Now fixed in v2.1, as the user is free to define the species they run with and add new ones. See https://github.com/chrisroadmap/fair-add-hfc.
