### ISSUE TITLE
RCP 1.9

### ISSUE THREAD

**Issue by Hans-PeterH** [OMS-NetZero/FAIR#59]
Are there plans to integrate data for RCP 1.9 into FaIR?

Does anyone know whether there is a public available dataset for RCP 1.9 having the same structure as the data for the other RCPs? Until now I found only data in the SSP database for some gases and 10 year intervals.

**Comment by znicholls** [comment]
> Does anyone know whether there is a public available dataset for RCP 1.9 having the same structure as the data for the other RCPs?

Not yet, it will come out as part of the publication on the process to derive the SSP GHG concentrations (the paper will be published as Meinshausen et al. 2019).

**Comment by Hans-PeterH** [comment]
@znicholls Thanks for the info.

**Comment by znicholls** [comment]
@Hans-PeterH if you're still interested I'd direct you to the RCMIP protocol (rcmip.org, specifically https://www.rcmip.org/#h.p_7MDJE6a8SpvT). The associated paper is https://gmd.copernicus.org/preprints/gmd-2019-375/. If that works, can you close this?

**Comment by Hans-PeterH** [comment]
@znicholls thanks for the link to the data and the paper.
