### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by znicholls** [OMS-NetZero/FAIR#6]
Not sure exactly what kind of set up we want yet but some initial thoughts:
- some sort of linter
- automated test suite of both simple run cases (e.g. no emissions gives no temp change, response to doubling of CO2 etc.) and installation

**Comment by chrisroadmap** [comment]
First test should be to see whether 

```
import fair
fair.__version__
```

doesn't result in an import error and returns a sensible answer (currently 1.1-x.abcdefgh, where x is the revision number and abcdefgh is the revision hash).

**Comment by chrisroadmap** [comment]
I'm about to get acquainted with [travis-ci](https://travis-ci.org). It is free for open source projects and requires access to our repository under [OAuth](https://help.github.com/articles/authorizing-oauth-apps/). I've screenshotted the data it wants access to, below. Happy to proceed?

![image](https://user-images.githubusercontent.com/7061148/34937042-481796fa-f9db-11e7-889a-46839786f247.png)

**Comment by znicholls** [comment]
Fine by me

**Comment by chrisroadmap** [comment]
I have travis-ci working on the `unit_tests` branch which automates the pytest script every time you commit and I get an email notification that tell you whether it passes or fails. It's pretty cool. Lots more we can do with this but a good start. I like the idea of embedding a status badge into the README.md file (check out shields.io) that dynamically updates the build status. Will pull request this branch before I start making some science improvements on FAIR.

**Comment by znicholls** [comment]
Wicked sounds awesome!
