### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by znicholls** [OMS-NetZero/FAIR#6]
Can we please decide on a convention for indentation? At the moment I'm using tabs (4 space width) and you're using 2 spaces and eventually one of us is going to throw a computer out the window if we don't agree.

**Comment by richardcode** [comment]
I think we should avoid tabs as they can cause problems in some editors.
http://www.secnetix.de/olli/Python/block_indentation.hawk

**Comment by znicholls** [comment]
Sounds sensible, I think we should follow this https://www.python.org/dev/peps/pep-0008/

**Comment by richardcode** [comment]
Agreed! Let's try to stick to this convention.
