### ISSUE TITLE
Cowtan and Way data

### ISSUE THREAD

**Issue by TeddyHornsby** [OMS-NetZero/FAIR#67]
Hi all, sorry if this is a stupid question! I was wondering if any of you have a reference for the Cowtan and Way data held within the FaIR download? The documentation is a little unclear on where it comes from and I can only find data online for the original source up to 2014.

Cheers,
Teddy

**Comment by znicholls** [comment]
Hi Teddy, 

Not a stupid question at all. You can download it from http://www-users.york.ac.uk/~kdc3/papers/coverage2013/series.html (search for 'HadCRUT4 infilled by kriging' under the 'Version 2.0' heading).

If you use `wget`, you can simply do

```sh
wget http://www-users.york.ac.uk/~kdc3/papers/coverage2013/had4_krig_v2_0_0.txt
```

Hope that works,

Zeb

**Comment by TeddyHornsby** [comment]
Excellent thanks very much!

**Comment by chrisroadmap** [comment]
Cheers @znicholls, I'll close this but feel free to re-open with any follow up questions.
