### ISSUE TITLE
Breakdown of Etminan CO2 forcing relationship

### ISSUE THREAD

**Issue by chrisroadmap** [OMS-NetZero/FAIR#72]
Above about 3000 ppm CO2 the non-logarithmic terms in the Etminan relationship start to dominate and produce CO2 forcing that is no longer monotonically increasing with CO2 concentrations. Above around 6600 ppm the forcing for increasing CO2 turns negative! In their defence the relationship was not trained to fit such high values of concentrations, but should users ever want to investigate palaeo conditions (not recommended currently, but a possible additional future feature) then this should be considered.

To avoid this, users are free to choose AR5 forcing relationships (select `ghg_forcing='Myhre'` in call to `fair_scm`). A nice solution would be to seamlessly transition from Etminan to Myhre depending on concentrations of CO2, CH4 and N2O.

**Comment by Hans-PeterH** [comment]
Meinshausen et al. (2019; https://doi.org/10.5194/gmd-2019-222, Section 2.7) suggest a modification of the formulas of Etminan et al. which is valid for higher concentrations. Do you plan to include these formulas into FaIR such that a transition from Etminan to Myhre is no longer necessary?

**Comment by chrisroadmap** [comment]
Excellent suggestion! I will do this next week when at my desk.

**Comment by Hans-PeterH** [comment]
Thanks!
