### ISSUE TITLE
Deletion of multi_gas branch

### ISSUE THREAD

**Issue by chrisroadmap** [OMS-NetZero/FAIR#8]
This is the branch that was ported over from FAIR-pro but had a different commit history and it was too difficult to merge into the main code so I started from scratch with branch_1.1.0 which has now been merged in. It should now be safe to delete multi_gas which will clean up the repo but I just wanted to make sure.

**Comment by znicholls** [comment]
If you're happy to delete it I'm happy, @richardcode ?

**Comment by richardcode** [comment]
@chrisroadmap @znicholls yes, let's go ahead and delete this.

**Comment by chrisroadmap** [comment]
Done!
